# Generated by Django 5.2.6 on 2025-09-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
